### PR TITLE
Feature tests!

### PR DESCRIPTION
**Pull request by ajm188**
Wrote a basic feature test. I've never done this before, so I don't really know what I'm doing and would appreciate feedback, no matter how nit-picky.

Especially from @StephHippo. Also, let's push more feature tests to this branch before merging.

### CODE REVIEW

**Comment by ajm188** [comment]
@StephHippo updated for your reviewing pleasure

**Comment by StephHippo** [comment]
:+1: These look great. Merging them in so I can start adding to them.

**Comment by StephHippo** [comment]
Reopening because I hit the wrong button.

**Comment by StephHippo** [comment]
Merging this myself because I'm working on it now.

**Pull request merged**
